set dotenv-load := true

# default lists actions
default:
  @just -f {{ source_file() }} --list

# can be applied anytime
home: 
  #!/usr/bin/env bash
  home-manager switch --flake .#chrisguest@nix5530-nixos

# requires sudo -i
config: 
  #!/usr/bin/env bash
  nixos-rebuild switch --flake .#nix5530-nixos

monitor-gpu:
  #!/usr/bin/env bash
  tmuxinator start -p ./monitor-gpu.yaml

