# syntax=docker/dockerfile:1.4
FROM nixos/nix:latest AS BUILDER

WORKDIR /scratch
COPY sox.nix sox.nix
RUN nix-build ./sox.nix

#RUN find /nix/store -name "libsox.so.3" 
RUN find /nix/store -name "ldd" 

# NOTE: Escape the \$ otherwise they are rendered at buildtime
COPY <<EOF /scratch/exportldd.sh
#!/usr/bin/env bash
/nix/store/h0cnbmfcn93xm5dg2x27ixhag1cwndga-glibc-2.34-210-bin/bin/ldd "./result/bin/sox" >  /scratch/sox_libs.txt
cat /scratch/sox_libs.txt | /nix/store/w3p77mkdy3pigg12iyha8y9dqakhjsxn-gawk-5.1.1/bin/awk 'NF == 4 { {print \$3} }' > /scratch/sox_libs_extracted.txt    
cat /scratch/sox_libs_extracted.txt | /nix/store/w3p77mkdy3pigg12iyha8y9dqakhjsxn-gawk-5.1.1/bin/awk -F/ -vOFS=/ '{ print \$1,\$2,\$3,\$4; }' | sort -u > /scratch/sox_libs_paths.txt
EOF
RUN chmod +x /scratch/exportldd.sh
RUN /scratch/exportldd.sh
CMD ["./result/bin/sox", "--version"]


# # NOTE: Use this target to work out what to copy into scratch or distroless container.
# FROM ubuntu:22.04 AS LDD

# COPY --from=BUILDER /scratch/result/bin/ /bin/
# RUN ldd /bin/sox


#FROM ubuntu:22.04 AS PRODUCTION
#FROM gcr.io/distroless/base AS PRODUCTION
FROM gcr.io/distroless/nodejs:16 AS PRODUCTION

COPY --from=BUILDER /scratch/result/bin/ /bin/

#COPY --from=BUILDER /nix /nix
COPY --from=BUILDER /nix/store/1d73jni11fmzdb748h0p97w6s184a6hm-libpulseaudio-15.0 /nix/store/1d73jni11fmzdb748h0p97w6s184a6hm-libpulseaudio-15.0
COPY --from=BUILDER /nix/store/1lq1sc9xrwznmiikbikr3apimp8ivkr3-flac-1.3.4 /nix/store/1lq1sc9xrwznmiikbikr3apimp8ivkr3-flac-1.3.4
COPY --from=BUILDER /nix/store/42j3drc4myyd5y3agh78z91mv19g6gba-libgpg-error-1.42 /nix/store/42j3drc4myyd5y3agh78z91mv19g6gba-libgpg-error-1.42
COPY --from=BUILDER /nix/store/4s6qqqmpn3v4kcp5s86pshdmn6mnz8jz-libmad-0.15.1b /nix/store/4s6qqqmpn3v4kcp5s86pshdmn6mnz8jz-libmad-0.15.1b
COPY --from=BUILDER /nix/store/4x0a0ghr6210j0lk6kkp6szzf86c7ig1-libvorbis-1.3.7 /nix/store/4x0a0ghr6210j0lk6kkp6szzf86c7ig1-libvorbis-1.3.7
COPY --from=BUILDER /nix/store/4zswgxs21xkyb454y26whslhr02y2wip-libpng-apng-1.6.37 /nix/store/4zswgxs21xkyb454y26whslhr02y2wip-libpng-apng-1.6.37
COPY --from=BUILDER /nix/store/ah4v698rcxrk47pg40am42jfrhzy15gm-libao-1.2.2 /nix/store/ah4v698rcxrk47pg40am42jfrhzy15gm-libao-1.2.2
COPY --from=BUILDER /nix/store/bl9mc8ggkgiwdcpz1iswg1jrjzwn9jj9-opusfile-0.12 /nix/store/bl9mc8ggkgiwdcpz1iswg1jrjzwn9jj9-opusfile-0.12
COPY --from=BUILDER /nix/store/cki6zalbpin96q7k33a1s26ffmbqvr4r-xz-5.2.5 /nix/store/cki6zalbpin96q7k33a1s26ffmbqvr4r-xz-5.2.5
COPY --from=BUILDER /nix/store/d01894jn8xcgqgs3gdvil7pvxq4rkmv5-alsa-lib-1.2.6.1 /nix/store/d01894jn8xcgqgs3gdvil7pvxq4rkmv5-alsa-lib-1.2.6.1
COPY --from=BUILDER /nix/store/d0nndqq9hl05h7dkpqh4zfjv4xcj1bs9-sox-unstable-2021-05-09 /nix/store/d0nndqq9hl05h7dkpqh4zfjv4xcj1bs9-sox-unstable-2021-05-09
COPY --from=BUILDER /nix/store/d3f15y0p9iy2wp4k31qj96l3pn3gqyjf-lz4-1.9.3 /nix/store/d3f15y0p9iy2wp4k31qj96l3pn3gqyjf-lz4-1.9.3
COPY --from=BUILDER /nix/store/gnv9dj2blgf495gqg3w7mqvkgrlps9cq-wavpack-5.4.0 /nix/store/gnv9dj2blgf495gqg3w7mqvkgrlps9cq-wavpack-5.4.0
COPY --from=BUILDER /nix/store/iirqa1lqni18mcaii3g1l5s15jxwz17a-systemd-250.4 /nix/store/iirqa1lqni18mcaii3g1l5s15jxwz17a-systemd-250.4
COPY --from=BUILDER /nix/store/j132k1ncfn6gjfd2f5s1gz37170rch4h-gcc-11.3.0-lib /nix/store/j132k1ncfn6gjfd2f5s1gz37170rch4h-gcc-11.3.0-lib
COPY --from=BUILDER /nix/store/j2dzkjzp7hmckz4ngsf987lynj1mnw5a-libtool-2.4.7-lib /nix/store/j2dzkjzp7hmckz4ngsf987lynj1mnw5a-libtool-2.4.7-lib
COPY --from=BUILDER /nix/store/ja1iw47v9jkfgnj97l5cjivzn84160w2-file-5.41 /nix/store/ja1iw47v9jkfgnj97l5cjivzn84160w2-file-5.41
COPY --from=BUILDER /nix/store/jnwakqh1c5f93wk0aynliwynan02h3wc-libsndfile-1.1.0 /nix/store/jnwakqh1c5f93wk0aynliwynan02h3wc-libsndfile-1.1.0
COPY --from=BUILDER /nix/store/l7j222k357y8fbh9gj283mv7s1nh1vrx-zstd-1.5.2 /nix/store/l7j222k357y8fbh9gj283mv7s1nh1vrx-zstd-1.5.2
COPY --from=BUILDER /nix/store/lg3lzl0dhrrnkcdpzw3ajvcxsi40fi90-libopus-1.3.1 /nix/store/lg3lzl0dhrrnkcdpzw3ajvcxsi40fi90-libopus-1.3.1
COPY --from=BUILDER /nix/store/ng6q1fyiiakhbi8iay60bky1iddzj9g8-libogg-1.3.5 /nix/store/ng6q1fyiiakhbi8iay60bky1iddzj9g8-libogg-1.3.5
COPY --from=BUILDER /nix/store/q38q8ng57zwjg1h15ry5zx0lb0xyax4b-libcap-2.63-lib /nix/store/q38q8ng57zwjg1h15ry5zx0lb0xyax4b-libcap-2.63-lib
COPY --from=BUILDER /nix/store/q7k32ydcqlram7f0l6b1y2c4cs07765y-zlib-1.2.12 /nix/store/q7k32ydcqlram7f0l6b1y2c4cs07765y-zlib-1.2.12
COPY --from=BUILDER /nix/store/qmiac2nwj4b8wqid349srr82gy6ijl8v-libgcrypt-1.10.1 /nix/store/qmiac2nwj4b8wqid349srr82gy6ijl8v-libgcrypt-1.10.1
COPY --from=BUILDER /nix/store/scd5n7xsn0hh0lvhhnycr9gx0h8xfzsl-glibc-2.34-210 /nix/store/scd5n7xsn0hh0lvhhnycr9gx0h8xfzsl-glibc-2.34-210
COPY --from=BUILDER /nix/store/yhhlsm8cl2b5lkb4vznbq4yczmnavrcq-dbus-1.14.0-lib /nix/store/yhhlsm8cl2b5lkb4vznbq4yczmnavrcq-dbus-1.14.0-lib

CMD ["/bin/sox", "--version"]
