set dotenv-load := true

# default lists actions
default:
  @just -f {{ source_file() }} --list

# can be applied anytime
home: 
  #!/usr/bin/env bash
  home-manager switch --flake .#chrisguest@bigmonga-nixos

# requires sudo -i
config: 
  #!/usr/bin/env bash
  nixos-rebuild switch --flake .#bigmonga-nixos

